# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Drew Lindsay
# Description of the Site
description: Computational biologist | Data scientist | Software developer | Open source enthusiast
description_short: Computational biologist, etc
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: biology, bioinformatics, computational
# URL for the Image of custom Favicon
favicon-url: /assets/images/avatar.png
site-avatar: /assets/images/avatar.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: andr.lindsay@gmail.com
twitter_username: nerdyaswild
instagram_username: nerdyaswild
linkedin_username: andrew-lindsay-868925196
github_username:  knacko
youtube_channel_id:
orc_id: 0000-0001-6607-5812
stackoverflow_id: 1451667
spotify_username: o8jkslw1ca3xo412kmsgghg5i
kaggle_username: nerdyaswild

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname:

# Name of the Author
author-name: Drew Lindsay
# URL for the Image of the Author
author-image: /assets/images/avatar.png
# 60 Words About the Author
author-about: I am a molecular biology MSc graduate student who focused on cancer biology at the<a href="https://www.uni-heidelberg.de/en">University of Heidelberg</a>/<a href="https://www.dkfz.de/en/index.html">German Cancer Research Center.</a>Previously, I've previously been involved with the<a href="http://agogbio.unsw.edu.au/">Australian Genomics and Clinical Outcomes of Glioma</a>project at the University in New South Wales and the<a href="https://eithealth.eu/project/sensus/">SensUs project</a>with EIT Health and Uppsala Universitet/University of Eindhoven. My work has been both wet and dry, from developing a new<a href="https://github.com/knacko/F022-Multiplex-Serology-Dashboard">blood assay</a>for Syphilis to developing new<a href="https://github.com/knacko/scMethrix">bioinformatic tools</a>for investigating patient epigenomics.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: knacko.github.io

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
